### ISSUE TITLE
Test failure: `XdsRouteServiceTest`

### ISSUE THREAD

**Issue by ikhoon** [line/centraldogma#1014]
```
> Task :xds:shadedTest FAILED
XdsRouteServiceTest > initializationError FAILED
    java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to start control plane plugin in 60 seconds.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:714)
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
        at com.linecorp.armeria.common.util.UnmodifiableFuture.doCompleteExceptionally(UnmodifiableFuture.java:179)
        at com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:113)
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
        at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:164)
        at com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:115)
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:753)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:262)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)

        Caused by:

27 tests completed, 1 failed
        java.lang.RuntimeException: Failed to start control plane plugin in 60 seconds.
            at com.linecorp.centraldogma.xds.internal.ControlPlanePlugin.init(ControlPlanePlugin.java:49)
            at com.linecorp.centraldogma.server.CentralDogma.lambda$startServer$6(CentralDogma.java:652)
            at com.linecorp.centraldogma.internal.shaded.guava.collect.ImmutableList.forEach(ImmutableList.java:423)
            at com.linecorp.centraldogma.server.CentralDogma.startServer(CentralDogma.java:647)
            at com.linecorp.centraldogma.server.CentralDogma.doStart(CentralDogma.java:424)
            at com.linecorp.centraldogma.server.CentralDogma.access$700(CentralDogma.java:188)
            at com.linecorp.centraldogma.server.CentralDogma$CentralDogmaStartStop.lambda$doStart$0(CentralDogma.java:1116)
            at com.linecorp.centraldogma.server.CentralDogma$CentralDogmaStartStop.lambda$execute$2(CentralDogma.java:1152)
            ... 1 more

            Caused by:
            java.util.concurrent.TimeoutException
                at java.util.concurrent.FutureTask.get(FutureTask.java:205)
                at com.linecorp.centraldogma.xds.internal.ControlPlanePlugin.init(ControlPlanePlugin.java:47)
                ... 8 more
```

**Comment by minwoox** [comment]
https://github.com/line/centraldogma/pull/980/commits/0885bf201c468c0f89ea0ef428e38b4fea691094
Will fix this issue. :wink:

**Comment by minwoox** [comment]
Closed by #980

**Comment by ikhoon** [comment]
It still seems to fail intermittently.
https://github.com/line/centraldogma/actions/runs/10416575524/job/28849089012#step:6:2043

**Comment by minwoox** [comment]
Oops, let's leave it as a known issue.
It's just that it takes approximately 5 seconds to load the files and there are multiple tests to access the files.

**Comment by ikhoon** [comment]
Would it be better to mark it as `FlakyTest` because I also encountered it when trying to upload artifacts? However, the second trial finished successfully.
https://github.com/line/centraldogma/actions/runs/10417095174/job/28850627317#step:5:1946

**Comment by minwoox** [comment]
If so, we have to mark all tests with `@FlakyTest` in the xds module. Let me see if I can reduce the time.
