### ISSUE TITLE
Gracefully stop the mirror scheduling job when a server stops

### ISSUE THREAD

**Issue by ikhoon** [line/centraldogma#1074]
If a mirror job is stopped while performing Git operations, the data of Git is broken and the next fetch fails with the following error. 
```java
com.linecorp.centraldogma.server.mirror.git.GitMirrorException: 
  Failed to fetch the remote repository 'xxxx/yyy.git' to the local repository '/'. 
  (reason: Expected ACK/NAK, got: shallow fb187e8ccee78bddad8f026f6fcee4be8eed614a
	at com.linecorp.centraldogma.server.internal.mirror.AbstractGitMirror.mirrorRemoteToLocal(AbstractGitMirror.java:274)
	at com.linecorp.centraldogma.server.internal.mirror.SshGitMirror.mirrorRemoteToLocal(SshGitMirror.java:119)
	at com.linecorp.centraldogma.server.internal.mirror.AbstractMirror.mirror(AbstractMirror.java:185)
	at com.linecorp.centraldogma.server.internal.mirror.InstrumentedMirroringJob.lambda$run$0(InstrumentedMirroringJob.java:66)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:69)
	at com.linecorp.centraldogma.server.internal.mirror.InstrumentedMirroringJob.run(InstrumentedMirroringJob.java:65)
	at com.linecorp.centraldogma.server.internal.mirror.MirrorSchedulingService.run(MirrorSchedulingService.java:252)
	at com.linecorp.centraldogma.server.internal.mirror.MirrorSchedulingService.lambda$runAsync$5(MirrorSchedulingService.java:244)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76
```

**Comment by ikhoon** [comment]
Fixed by #1104
