### ISSUE TITLE
Test failure: `XdsMemberPermissionTest`

### ISSUE THREAD

**Issue by Sabadon** [line/centraldogma#1077]
XdsMemberPermissionTest fails on my PC
```Expecting ArrayList:
  ["foo"]
to contain only:
  ["foo", "@xds"]
but could not find the following element(s):
  ["@xds"]

java.lang.AssertionError: 
Expecting ArrayList:
  ["foo"]
to contain only:
  ["foo", "@xds"]
but could not find the following element(s):
  ["@xds"]

	at com.linecorp.centraldogma.server.test.XdsMemberPermissionTest.shouldAllowMembersToAccessInternalProjects(XdsMemberPermissionTest.java:156)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
```

**Comment by Sabadon** [comment]
I noticed that if I add Thread.sleep or even some small operation, for example `userClient.listProjects().join().forEach(System.out::println);`, before the line where the error occurs, the test completes successfully.

**Comment by minwoox** [comment]
That's a flaky test that we need to fix. Thanks for the report. 😉

**Comment by Sabadon** [comment]
I want to contribute, and so far I have 2 ideas on how to solve the problem:
1. Use a Watcher to wait for changes in the metadata, but I'm not sure if it's possible to monitor changes in the metadata through this API.
2. Use await().untilAsserted, but I think the first solution would be more preferable.  
Could you let me know if any of the solutions I proposed are acceptable? Or should this problem be solved not at the testing level?

**Comment by jrhee17** [comment]
Probably just using `await().untilAsserted` sounds fine to me

**Comment by minwoox** [comment]
closed by #1083
