### ISSUE TITLE
Do not stop mirroring scheduler

### ISSUE THREAD

**Issue by hyangtack** [line/centraldogma#245]
I have no idea why `meta` repository didn't exist at that time. Anyway it would be better that we make the mirroring scheduler not stopped even when an exception is raised during scheduling mirroring job.

```
[ERROR](c.l.c.s.i.m.DefaultMirroringService) [mirroring-scheduler-6-1] Git-to-CD mirroring scheduler stopped due to an unexpected ex
ception:
com.linecorp.centraldogma.common.RepositoryNotFoundException: meta
    at com.linecorp.centraldogma.server.internal.storage.repository.RepositoryManagerWrapper.get(RepositoryManagerWrapper.java:66)
    at com.linecorp.centraldogma.server.internal.storage.repository.RepositoryManagerWrapper.get(RepositoryManagerWrapper.java:36)
    at com.linecorp.centraldogma.server.internal.storage.project.DefaultProject.metaRepo(DefaultProject.java:78)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at com.linecorp.centraldogma.server.internal.mirror.DefaultMirroringService.schedulePendingMirrors(DefaultMirroringService.java:185)
    at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:630)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by trustin** [comment]
The reason why `meta` repo did not exist is because the project was in the middle of creation, i.e. the project was created but its `meta` repository was not yet. See `ProjectInitializingCommandExecutor` which is the source of the race condition.
