### ISSUE TITLE
Flaky test: ZooKeeperCommandExecutorTest.testLogWatch

### ISSUE THREAD

**Issue by minwoox** [line/centraldogma#28]
```
2017-10-10 09:11:10.711 [INFO ](c.l.c.s.i.r.ZooKeeperCommandExecutor) [Curator-LeaderSelector-1] Releasing leadership: m2
2017-10-10 09:11:10.718 [ERROR](o.a.c.f.r.l.LeaderSelector) [Curator-LeaderSelector-1] The leader threw an exception
java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.delete(CuratorFrameworkImpl.java:359)
	at org.apache.curator.framework.recipes.locks.LockInternals.deleteOurPath(LockInternals.java:339)
	at org.apache.curator.framework.recipes.locks.LockInternals.releaseLock(LockInternals.java:123)
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:154)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:449)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:466)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:65)
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:246)
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:240)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by minwoox** [comment]
This is not a failed test.
