### ISSUE TITLE
Flaky test: GitRepositoryTest.testHistory_correctRangeOfResult

### ISSUE THREAD

**Issue by hyangtack** [line/centraldogma#32]
```
GitRepositoryTest.testHistory_correctRangeOfResult: FAILURE
com.linecorp.centraldogma.server.internal.storage.repository.git.GitRepositoryTest > testHistory_correctRangeOfResult FAILED
    org.junit.ComparisonFailure: expected:<Revision([4])> but was:<Revision([5])>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.linecorp.centraldogma.server.internal.storage.repository.git.GitRepositoryTest.testHistory_correctRangeOfResult(GitRepositoryTest.java:708)
```

**Comment by minwoox** [comment]
We share the same repository in the test and look like that makes us fall in the race condition. Is it a burden to have individual repository for each test cases?

**Comment by minwoox** [comment]
Or at least, the tests which compare the revision number?
