### ISSUE TITLE
Send '503 Service Unavailable' when handling a request already timed out

### ISSUE THREAD

**Issue by trustin** [line/centraldogma#392]
`IllegalStateException: Request already timed out` has to be translated to `503 Service Unavailable` but it is currently being translated to `500 Internal Server Error`:

```
[WARN] (CentralDogmaExceptions.java:77) Unexpected exception with error code INTERNAL_SERVER_ERROR (2) from: watchFile()
com.linecorp.centraldogma.internal.thrift.CentralDogmaException: java.lang.IllegalStateException: Request already timed out.
 at com.linecorp.centraldogma.server.internal.thrift.Converter.convert(Converter.java:215)
 at com.linecorp.centraldogma.server.internal.thrift.CentralDogmaServiceImpl.logAndInvokeOnError(CentralDogmaServiceImpl.java:396)
 at com.linecorp.centraldogma.server.internal.thrift.CentralDogmaServiceImpl.lambda$handleWatchFileResult$24(CentralDogmaServiceImpl.java:388)
 at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
 at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
 at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
 at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
 at com.linecorp.armeria.common.util.Functions.lambda$voidFunction$0(Functions.java:182)
 at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
 at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
 at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
 at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
 at com.linecorp.centraldogma.server.internal.storage.repository.cache.CachingRepository.lambda$null$3(CachingRepository.java:199)
 ...
Caused by: java.lang.IllegalStateException: Request already timed out.
```

**Comment by hyangtack** [comment]
Regarding the legacy client, do we need to add one more error code and exception class for this?

https://github.com/line/centraldogma/blob/master/client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogma.java#L582

**Comment by hyangtack** [comment]
Added a log message by #401 because it's hard to find a root cause of this log.

**Comment by trustin** [comment]
https://github.com/line/armeria/issues/1839 needs to be resolved first.
