### ISSUE TITLE
Test failed during configuration of the build environment.

### ISSUE THREAD

**Issue by geminiKim** [line/centraldogma#440]
Hi! I'm interested in this project. 😄 

By the way, I found that the test failed while configuring the build environment.

I'm not sure but this test seems to fail because I can't connect to the repository of `Line`. (`ssh://git@github.com:22/line/centraldogma-authtest.git`)

Are there any settings I missed?

More detail :
```
// Failed-Test : 'GitMirrorAuthTest'.'testAuth'
// Detail Errors :

java.util.concurrent.CompletionException: com.linecorp.centraldogma.server.MirrorException: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin

	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.linecorp.centraldogma.server.MirrorException: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
	at com.linecorp.centraldogma.server.internal.mirror.AbstractMirror.mirror(AbstractMirror.java:153)
	at com.linecorp.centraldogma.server.internal.mirror.DefaultMirroringService.run(DefaultMirroringService.java:224)
	at com.linecorp.centraldogma.server.internal.mirror.DefaultMirroringService.lambda$null$5(DefaultMirroringService.java:217)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.linecorp.centraldogma.server.internal.mirror.DefaultMirroringService.lambda$null$6(DefaultMirroringService.java:217)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.linecorp.centraldogma.server.internal.mirror.DefaultMirroringService.lambda$mirror$7(DefaultMirroringService.java:216)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	... 4 more
Caused by: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:252)
	at com.linecorp.centraldogma.server.internal.mirror.GitMirror.mirrorRemoteToLocal(GitMirror.java:102)
	at com.linecorp.centraldogma.server.internal.mirror.AbstractMirror.mirror(AbstractMirror.java:144)
	... 12 more
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: ssh://git@github.com:22/line/centraldogma-authtest.git: ERROR: Repository not found.

	at org.eclipse.jgit.transport.TransportGitSsh.cleanNotFound(TransportGitSsh.java:218)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:306)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:170)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:138)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:124)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1292)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:244)
	... 14 more
```

**Comment by trustin** [comment]
You need to exclude that test case for now because it requires you to be a member of LINE organization. Sorry about the inconvenience!

**Comment by geminiKim** [comment]
Thank you for fast feedback! Not a big inconvenience! 😄
