### ISSUE TITLE
Flaky test: `ZooKeeperCommandExecutorTest.hierarchicalQuorumsWithFailOver()`

### ISSUE THREAD

**Issue by ikhoon** [line/centraldogma#550]
https://ci.appveyor.com/project/line/centraldogma/builds/37320073#L886
```java
ZooKeeperCommandExecutorTest > hierarchicalQuorumsWithFailOver() FAILED
    java.util.concurrent.TimeoutException: hierarchicalQuorumsWithFailOver() timed out after 60 seconds
        at org.junit.jupiter.engine.extension.TimeoutInvocation.createTimeoutException(TimeoutInvocation.java:70)
        at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:59)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
```

**Comment by ikhoon** [comment]
When I tested it locally, sometimes, the test takes more than 60 seconds. 
I think this flaky test could be fixed by https://github.com/line/centraldogma/pull/549/commits/526bfdcf96581b83d0b7c8e4aec11b0c2675e71b
